platform :ios, '10.0'

target 'Flash Chat iOS13' do

  # Pods for Flash Chat iOS13
  pod 'CLTypingLabel', '~> 0.4.0'
  
  # add pods for desired Firebase products
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  
end
